package define


const (
	KEY_SECTION_DEMO     ="demo"
	KEY_SECTION_main     ="main"
	KEY_OPTION_target    ="target"
	KEY_OPTION_sheet     ="sheet"
	KEY_OPTION_xFindText ="xFindText"
	KEY_OPTION_yFindText ="yFindText"
	KEY_OPTION_xStartText       ="xStartText"
	KEY_OPTION_yStartText       ="yStartText"
	KEY_OPTION_xEndText         ="xEndText"
	KEY_OPTION_yEndText         ="yEndText"
	KEY_OPTION_operation        ="operation"
	KEY_OPTION_readRange        ="readRange"
	KEY_OPTION_readEndCondition ="readEndCondition"
	KEY_OPTION_process        ="process"
	KEY_OPTION_nextSection    ="nextSection"
	KEY_OPTION_format         ="format"
	KEY_OPTION_xAdd           ="xAdd"
	KEY_OPTION_yAdd           ="yAdd"
	KEY_OPTION_processSection ="processSection"
	KEY_OPTION_columnMap      ="columnMap"
	KEY_OPTION_hasData        ="hasData"
	KEY_OPTION_dstFile        ="dstFile"
	KEY_OPTION_srcFile        ="srcFile"
	KEY_OPTION_tableMap       ="tableMap"
	KEY_OPTION_srcColumn      ="srcColumn"
	KEY_OPTION_dstColumn      ="dstColumn"
	KEY_OPTION_key            ="key"
	KEY_OPTION_sumSection     ="sumSection"
	KEY_OPTION_value     ="value"



	KEY_VALUE_src             ="src"
	KEY_VALUE_dst             ="dst"
	KEY_VALUE_right           ="right"
	KEY_VALUE_down            ="down"
	KEY_VALUE_writeArray      ="writeArray"
	KEY_VALUE_readArray       ="readArray"
	KEY_VALUE_readItemProcess ="readItemProcess"
	KEY_VALUE_readItem			="readItem"
	//KEY_VALUE_writeItem			="writeItem"
	KEY_VALUE_string ="string"
	KEY_VALUE_float  ="float"
	KEY_VALUE_int    ="int"
	KEY_VALUE_date   ="date"
	KEY_VALUE_sum    ="sum"
	KEY_VALUE_sort   ="sort"
	KEY_VALUE_filter ="filter"
	KEY_VALUE_limt   ="limt"
	KEY_VALUE_reset  ="reset"
	KEY_VALUE_print  ="print"
	KEY_VALUE_compny ="$compny"
	//KEY_VALUE_top5          ="top5"
)


